name: Minecraft-Konziiis-Base-Defence
version: '${project.version}'
main: de.konziiis.minecraftkonziiisbasedefence.MinecraftKonziiisBaseDefence
api-version: 1.19
authors: [Caesar87, ma22he]
description: Plugin
website: konziiis.de


commands:
  hello:
    description: Foo command
    aliases:
      - foobar
      - fubar
    permission: test.foo
    permission-message: You do not have permission!
    usage: /<command> [test|stop]